MVC_Favotire_Song_List_Api/Models/ErrorViewModel.cs
namespace MVC_Favotire_Song_List_Api.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC_Favotire_Song_List_Api/Models/Song.cs
using System;
using System.Collections.Generic;

namespace MVC_Favotire_Song_List_Api.Models
{
    public partial class Song
    {
        public int Id { get; set; }
        public string Title { get; set; } = null!;
        public string Group { get; set; } = null!;
        public short Year { get; set; }
        public string Genre { get; set; } = null!;
    }
}

MVC_Favotire_Song_List_Api/Models/favorite_songsContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace MVC_Favotire_Song_List_Api.Models
{
    public partial class favorite_songsContext : DbContext
    {
        public favorite_songsContext()
        {
        }

        public favorite_songsContext(DbContextOptions<favorite_songsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Song> Songs { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
//                optionsBuilder.UseMySql("server=localhost;uid=root;pwd=LaContraseñaPropia;database=favorite_songs", Microsoft.EntityFrameworkCore.ServerVersion.Parse("8.0.30-mysql"));
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("utf8mb3_general_ci")
                .HasCharSet("utf8mb3");

            modelBuilder.Entity<Song>(entity =>
            {
                entity.ToTable("songs");

                entity.Property(e => e.Genre).HasMaxLength(50);

                entity.Property(e => e.Group).HasMaxLength(50);

                entity.Property(e => e.Title).HasMaxLength(100);

                entity.Property(e => e.Year).HasColumnType("year");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

MVC_Favotire_Song_List_Api/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Favotire_Song_List_Api.Models;
using System.Diagnostics;

namespace MVC_Favotire_Song_List_Api.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC_Favotire_Song_List_Api/Controllers/SongsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Favotire_Song_List_Api.Models;

namespace MVC_Favotire_Song_List_Api.Controllers
{
    public class SongsController : Controller
    {
        private readonly favorite_songsContext _context;

        public SongsController(favorite_songsContext context)
        {
            _context = context;
        }

        // GET: Songs
        public async Task<IActionResult> Index()
        {
              return _context.Songs != null ? 
                          View(await _context.Songs.ToListAsync()) :
                          Problem("Entity set 'favorite_songsContext.Songs'  is null.");
        }

        // GET: Songs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Songs == null)
            {
                return NotFound();
            }

            var song = await _context.Songs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (song == null)
            {
                return NotFound();
            }

            return View(song);
        }

        // GET: Songs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Songs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Group,Year,Genre")] Song song)
        {
            if (ModelState.IsValid)
            {
                _context.Add(song);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(song);
        }

        // GET: Songs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Songs == null)
            {
                return NotFound();
            }

            var song = await _context.Songs.FindAsync(id);
            if (song == null)
            {
                return NotFound();
            }
            return View(song);
        }

        // POST: Songs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Group,Year,Genre")] Song song)
        {
            if (id != song.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(song);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SongExists(song.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(song);
        }

        // GET: Songs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Songs == null)
            {
                return NotFound();
            }

            var song = await _context.Songs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (song == null)
            {
                return NotFound();
            }

            return View(song);
        }

        // POST: Songs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Songs == null)
            {
                return Problem("Entity set 'favorite_songsContext.Songs'  is null.");
            }
            var song = await _context.Songs.FindAsync(id);
            if (song != null)
            {
                _context.Songs.Remove(song);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SongExists(int id)
        {
          return (_context.Songs?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MVC_Favotire_Song_List_Api/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Favotire_Song_List_Api</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_Favotire_Song_List_Api.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mis Canciones Favoritas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Songs" asp-action="Index">Mi Lista</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="text-center">
            @*&copy; 2022 - MVC_Favotire_Song_List_Api - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
            Autor: Samuel Jiménez Milke. 2022. 
            @*<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC_Favotire_Song_List_Api/Views/Songs/Create.cshtml
@model MVC_Favotire_Song_List_Api.Models.Song

@{
    ViewData["Title"] = "Create";
}

<h1 style="padding-bottom: 50px">Agregar Canción</h1>

<h6 class="text-secondary">A continuación, ingresa la información de la canción a agregar:</h6>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="padding-bottom: 30px">
                <label asp-for="Title" class="control-label">Nombre</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding-bottom: 30px">
                <label asp-for="Group" class="control-label">Grupo/Autor</label>
                <input asp-for="Group" class="form-control" />
                <span asp-validation-for="Group" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding-bottom: 30px">
                <label asp-for="Year" class="control-label">Año de Publicación</label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding-bottom: 30px">
                <label asp-for="Genre" class="control-label">Genero Musical</label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Añadir Canción" class="btn btn-success" /> |
                <a asp-action="Index" class="btn-outline-secondary">
                    <button type="button" class="btn btn-outline-secondary">Regresar a mi Lista</button>
                </a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_Favotire_Song_List_Api/Views/Songs/Delete.cshtml
@model MVC_Favotire_Song_List_Api.Models.Song

@{
    ViewData["Title"] = "Delete";
}

<h1 style="padding-bottom: 50px">Eliminar Canción</h1>

<h6 class="text-secondary">Canción a Eliminar:</h6>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.Title)*@
            Titulo
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.Group)*@
            Grupu/Autor
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Group)
        </dd>
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.Year)*@
            Año de Estreno
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.Genre)*@
            Genero Musical
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">
            <button type="button" class="btn btn-outline-secondary">Regresar a mi lista</button>
        </a>
    </form>
</div>

MVC_Favotire_Song_List_Api/Views/Songs/Details.cshtml
@model MVC_Favotire_Song_List_Api.Models.Song

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.Title)*@
            Titulo
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.Group)*@
            Grupo/Autor
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Group)
        </dd>
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.Year)*@
            Año de Estreno
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.Genre)*@
            Genero Musical
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id"><button type="button" class="btn btn-outline-primary">Editar</button></a> |
    <a asp-action="Index" class="btn-outline-secondary"> <button type="button" class="btn btn-outline-secondary"> Regresar a mi Lista </button> </a>
</div>

MVC_Favotire_Song_List_Api/Views/Songs/Edit.cshtml
@model MVC_Favotire_Song_List_Api.Models.Song

@{
    ViewData["Title"] = "Edit";
}

<h1 style="padding-bottom: 50px">Editar</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group" style="padding-bottom: 30px">
                <label asp-for="Title" class="control-label">Titulo</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding-bottom: 30px">
                <label asp-for="Group" class="control-label">Grupo/Autor</label>
                <input asp-for="Group" class="form-control" />
                <span asp-validation-for="Group" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding-bottom: 30px">
                <label asp-for="Year" class="control-label">Año de Estreno</label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding-bottom: 30px">
                <label asp-for="Genre" class="control-label">Genero Musical</label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding-bottom: 30px">
                <input type="submit" value="Guardar" class="btn btn-primary" /> |
                <a asp-action="Index">
                    <button type="button" class="btn btn-outline-secondary">Regresar a mi Lista</button>
                </a>
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_Favotire_Song_List_Api/Views/Songs/Index.cshtml
@model IEnumerable<MVC_Favotire_Song_List_Api.Models.Song>

@{
    ViewData["Title"] = "Index";
}

<h1 style="padding-bottom: 50px">Mi Lista</h1>

<p>
    <a asp-action="Create">
        <button type="button" class="btn fw-light btn-outline-secondary">
            + Agregar Canción
        </button>
    </a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.Title)*@
                Titulo
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Group)*@
                Grupo/Autor
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Year)*@
                Año de Estreno
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Genre)*@
                Genero Musical
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Group)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>